name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # запустится только если test прошёл
    if: github.ref == 'refs/heads/master'  # только при пуше, не PR
    steps:
      - name: Deploy to VDS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_SSH_KEY }}
          fingerprint: ${{ secrets.VDS_FINGERPRINT }}
          script: |
            cd ./src
            git pull origin master
            uv sync
            # перезапуск если нужно, например:
            # systemctl restart myapp
